/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Foreground colors
        foreground: {
          DEFAULT: 'rgba(var(--foreground), 1)',
          revert: 'rgba(var(--coze-fg-revert), var(--coze-fg-revert-alpha))',
          white: 'rgba(var(--coze-fg-white), var(--coze-fg-white-alpha))',
          7: 'rgba(var(--coze-fg-7), 1)',
          6: 'rgba(var(--coze-fg-6), 1)',
          5: 'rgba(var(--coze-fg-5), var(--coze-fg-5-alpha))',
          4: 'rgba(var(--coze-fg-4), var(--coze-fg-4-alpha))',
          3: 'rgba(var(--coze-fg-3), var(--coze-fg-3-alpha))',
          2: 'rgba(var(--coze-fg-2), var(--coze-fg-2-alpha))',
          1: 'rgba(var(--coze-fg-1), var(--coze-fg-1-alpha))',
        },
        // Background colors
        background: {
          DEFAULT: 'rgba(var(--background), 1)',
          9: 'rgba(var(--coze-bg-9), var(--coze-bg-9-alpha))',
          8: 'rgba(var(--coze-bg-8), var(--coze-bg-8-alpha))',
          7: 'rgba(var(--coze-bg-7), var(--coze-bg-7-alpha))',
          6: 'rgba(var(--coze-bg-6), var(--coze-bg-6-alpha))',
          5: 'rgba(var(--coze-bg-5), var(--coze-bg-5-alpha))',
          4: 'rgba(var(--coze-bg-4), var(--coze-bg-4-alpha))',
          3: 'rgba(var(--coze-bg-3), var(--coze-bg-3-alpha))',
          2: 'rgba(var(--coze-bg-2), var(--coze-bg-2-alpha))',
          1: 'rgba(var(--coze-bg-1), var(--coze-bg-1-alpha))',
          0: 'rgba(var(--coze-bg-0), 1)',
        },
        // Brand colors
        brand: {
          DEFAULT: 'rgba(var(--coze-brand-7), 1)',
          50: 'rgba(var(--coze-brand-50), var(--coze-brand-50-alpha))',
          30: 'rgba(var(--coze-brand-30), var(--coze-brand-30-alpha))',
          7: 'rgba(var(--coze-brand-7), 1)',
          6: 'rgba(var(--coze-brand-6), 1)',
          5: 'rgba(var(--coze-brand-5), 1)',
          3: 'rgba(var(--coze-brand-3), var(--coze-brand-3-alpha))',
          2: 'rgba(var(--coze-brand-2), var(--coze-brand-2-alpha))',
          1: 'rgba(var(--coze-brand-1), var(--coze-brand-1-alpha))',
          0: 'rgba(var(--coze-brand-0), var(--coze-brand-0-alpha))',
        },
        // Functional colors
        red: {
          DEFAULT: 'rgba(var(--coze-red-7), 1)',
          7: 'rgba(var(--coze-red-7), 1)',
          6: 'rgba(var(--coze-red-6), 1)',
          5: 'rgba(var(--coze-red-5), 1)',
          3: 'rgba(var(--coze-red-3), var(--coze-red-3-alpha))',
          2: 'rgba(var(--coze-red-2), var(--coze-red-2-alpha))',
          1: 'rgba(var(--coze-red-1), var(--coze-red-1-alpha))',
          0: 'rgba(var(--coze-red-0), var(--coze-red-0-alpha))',
        },
        yellow: {
          DEFAULT: 'rgba(var(--coze-yellow-7), 1)',
          50: 'rgba(var(--coze-yellow-50), var(--coze-yellow-50-alpha))',
          30: 'rgba(var(--coze-yellow-30), var(--coze-yellow-30-alpha))',
          7: 'rgba(var(--coze-yellow-7), 1)',
          6: 'rgba(var(--coze-yellow-6), 1)',
          5: 'rgba(var(--coze-yellow-5), 1)',
          3: 'rgba(var(--coze-yellow-3), var(--coze-yellow-3-alpha))',
          2: 'rgba(var(--coze-yellow-2), var(--coze-yellow-2-alpha))',
          1: 'rgba(var(--coze-yellow-1), var(--coze-yellow-1-alpha))',
          0: 'rgba(var(--coze-yellow-0), var(--coze-yellow-0-alpha))',
        },
        green: {
          DEFAULT: 'rgba(var(--coze-green-7), 1)',
          7: 'rgba(var(--coze-green-7), 1)',
          6: 'rgba(var(--coze-green-6), 1)',
          5: 'rgba(var(--coze-green-5), 1)',
          3: 'rgba(var(--coze-green-3), var(--coze-green-3-alpha))',
          2: 'rgba(var(--coze-green-2), var(--coze-green-2-alpha))',
          1: 'rgba(var(--coze-green-1), var(--coze-green-1-alpha))',
          0: 'rgba(var(--coze-green-0), var(--coze-green-0-alpha))',
        },
        // Stroke colors
        stroke: {
          DEFAULT: 'rgba(var(--coze-stroke-5), var(--coze-stroke-5-alpha))',
          max: 'rgba(var(--coze-stroke-7), var(--coze-stroke-7-alpha))',
          6: 'rgba(var(--coze-stroke-6), var(--coze-stroke-6-alpha))',
          5: 'rgba(var(--coze-stroke-5), var(--coze-stroke-5-alpha))',
          opaque: 'rgb(var(--coze-stroke-opaque))',
        },
      },
      fontSize: {
        mini: '10px',
        base: '12px',
        lg: '14px',
        xl: '15px',
        xxl: '16px',
        '18px': '18px',
        '20px': '20px',
        '22px': '22px',
        '24px': '24px',
        '26px': '26px',
        '28px': '28px',
        '30px': '30px',
        '32px': '32px',
        '36px': '36px',
        '48px': '48px',
        '64px': '64px',
      },
      spacing: {
        DEFAULT: '8px',
        xxl: '96px',
        xl: '80px',
        md: '64px',
        mm: '48px',
        large: '40px',
        normal: '32px',
        small: '20px',
        mini: '16px',
        '1080px': '1080px',
        '800px': '800px',
        '640px': '640px',
        '480px': '480px',
        '320px': '320px',
        '240px': '240px',
        '200px': '200px',
        '160px': '160px',
        '120px': '120px',
        '96px': '96px',
        '80px': '80px',
        '64px': '64px',
        '48px': '48px',
        '40px': '40px',
        '32px': '32px',
        '30px': '30px',
        '28px': '28px',
        '26px': '26px',
        '24px': '24px',
        '22px': '22px',
        '20px': '20px',
        '18px': '18px',
        '16px': '16px',
        '15px': '15px',
        '14px': '14px',
        '12px': '12px',
        '10px': '10px',
        '9px': '9px',
        '8px': '8px',
        '6px': '6px',
        '5px': '5px',
        '4px': '4px',
        '3px': '3px',
        '2px': '2px',
        '1px': '1px',
      },
      borderRadius: {
        DEFAULT: '8px',
        ultra: '40px',
        xxl: '24px',
        xl: '16px',
        md: '12px',
        m: '10px',
        normal: '8px',
        small: '6px',
        little: '5px',
        mini: '4px',
        tiny: '2px',
      },
      boxShadow: {
        DEFAULT: '0 4px 12px 0px rgba(0, 0, 0, 0.08), 0px 8px 24px 0px rgba(0, 0, 0, 0.04)',
        small: '0px 2px 6px 0px rgba(0, 0, 0, 0.04), 0px 4px 12px 0px rgba(0, 0, 0, 0.02)',
        normal: '0 4px 12px 0px rgba(0, 0, 0, 0.08), 0px 8px 24px 0px rgba(0, 0, 0, 0.04)',
        large: '0px 8px 24px 0px rgba(0, 0, 0, 0.16), 0px 16px 48px 0px rgba(0, 0, 0, 0.08)',
      },
    },
  },
  plugins: [],
}
